In [4]:
import numpy as np
import matplotlib.pyplot as plt
import sympy as sym

In [12]:
# conventional technique used to solve for x: 3x = 1
# use of scalar inverse: 3^(-1)3x = 3^(-1)1

# 3^-1 is the inverse of 3

# application in linear algebra:
# Ax = b

# (A^-1)*(Ax) = (A^-1) * (b)

# since (A^-1) * (A) results in the identity matrix:
# Ix = A^-1 * b
# x = A^-1 * b

# required conditions for matrix inverse to exist:
# 1 must have square (same num of rows and cols)
# 2 full rank means all cols provide unque information

In [24]:
m = 5

A = np.random.randint(-5,5,(m,m))
Ainv = np.linalg.inv(A)

print(A)
print('\n') 
print(Ainv)

[[-4  0  1  0  2]
 [ 1 -1  3 -5 -4]
 [-4  3 -4  2 -3]
 [ 1 -4  1 -3 -4]
 [ 2  2  4  3 -5]]


[[-0.19968336  0.00257273 -0.06392242 -0.05026717 -0.00336434]
 [-0.070849    0.17435187  0.05264199 -0.25272116  0.00277063]
 [ 0.14347912  0.04076786 -0.08984762 -0.02731051  0.10053434]
 [ 0.03720562 -0.19770433 -0.01088462  0.09360776  0.10469028]
 [ 0.02889373 -0.01523847 -0.08292104 -0.08687908 -0.05699584]]
